#! /bin/tcsh -f

# This the main NetMHCIIpan 1.1 script. It only acts as the frontend to the
# software proper, a compiled binary.
# 
# VERSION:	2010 April 14	launch
# 

###############################################################################
#               GENERAL SETTINGS: CUSTOMIZE TO YOUR SITE
###############################################################################

# full path to the NetMHCIIpan 2.0 directory (mandatory)
setenv	NMHOME	/home/naz/Programs/netMHCIIpan-2.0

# determine where to store temporary files (must be writable to all users)
setenv	TMPDIR	/home/naz/tmp/tmpNetMHCPanII

# determine platform (do not change this unless you don't have 'uname'!)
setenv	UNIX	`uname -s`
setenv	AR	`uname -m`

###############################################################################
#               NOTHING SHOULD NEED CHANGING BELOW THIS LINE!
###############################################################################

#source /usr/cbs/etc/cshrc

# other settings
set PLATFORM = `echo $UNIX $AR | awk '{print $1"_"$2}'`
setenv NETMHCIIpan $NMHOME/$PLATFORM


# main ========================================================================
if ( -x $NETMHCIIpan/bin/netMHCIIpan ) then
   $NETMHCIIpan/bin/netMHCIIpan $*
else
   echo netMHCIIpan: no binaries found for $PLATFORM
endif

# end of script ===============================================================
